version: '3'
services:
  web:
    image: movie:latest
    container_name: movie_web
    ports:
    - "8080:8080"
    links:
    - redis
    environment:
    - REDIS_URL=redis
  redis:
    image: redis
    container_name: movie_redis